### ISSUE TITLE
Should additional testing of ironic take place, and if so, what?

### ISSUE THREAD

**Issue by juliakreger** [juliakreger/bifrost#8]
A number of additional tests come to mind that could be leveraged by Ansible to check the state of the standalone Ironic node, although the question becomes what would be efficient, reasonable, and relatively comprehensive based on our use case and what we've already verified by testing that we've stood a node up via Ironic.

Thoughts? Ramblings? Beuller?

**Comment by devananda** [comment]
After a basic test, I might run tempest against the ironic api service.
This could mean using the "fake" driver for api exercises, which Ansible
isn't going to provide,  or teaching tempest how to do functional deploys
directly in ironic. Or both. We should do both.

Other things that come to mind (upgrade, multi-conductor, ...) are
currently handled by other tools (grenade) or would expand the scope of
bifrost (multiple conductors would be a significant departure from the
initial project goals, and not a direction I'd like to go right now).

Hmm. There are probably other things too...

**Comment by juliakreger** [comment]
Having Ansible swap the configuration file for one that has the fake driver defined, and then firing up tempest seems like a fairly easy thing to do, although we would likely want to turn cleaning off if we got to the point of running tempest against functional deploys, but that seems later down the road.

For what its worth, I already set cleaning to be disabled for the test sequence in commit 659e97a812b81c45185ff028517940a16f3de2c6.

**Comment by Shrews** [comment]
Until we can solve the requirement for VMs to have 3GB of RAM (due to using DiB), automated testing using the fake driver is not going to be feasible since tempest tests requires, IIRC, at least 2 nodes to be available for parallel testing (it might be 3). That is too much of a memory requirement for the current testing infrastructure.

**Comment by juliakreger** [comment]
That is a very good point.  Although I wonder if we could load up/deploy cirros for functional testing since I think that lowers our RAM requirement to 1GB per VM.

Since I had this information at my finger tips regarding 8GB of ram, below is a snapshot from a system running Bifrost performing a deployment of multiple physical nodes.  Anyone know if testing nodes get a little swap space?

jkreger@testhost:/var/log/upstart$ free
             total       used       free     shared    buffers     cached
Mem:       8160032    7945580     214452     351044     198988    6895728
-/+ buffers/cache:     850864    7309168
Swap:      8370172     216884    8153288
jkreger@testhost:/var/log/upstart$

**Comment by Shrews** [comment]
Fairly certain that the HP Cloud and Rax cloud instances being used do not have any swap, but someone on the Infra team can say for sure.

**Comment by juliakreger** [comment]
That actually makes sense given the way the kernel handles RAM and prefers to use it for buffers and cache. =(

**Comment by juliakreger** [comment]
I went ahead and took a look at tempest this week and this will ultimately require teaching it about no-auth and how to do deployments without nova.  Not simple lifts in my mind, although I have received interest in using Bifrost to help facilitate CI testing, so we may have some help on that front.  I'll know more this next week.

If it comes down to it, It might be worthwhile to have a discussion with tempest folk in Vancouver and gauge their receptiveness to the addition of support for no-auth mode so we can leverage tempest.

In the mean time, I believe the best path is to improve the Ansible modules such that state can be verified cleanly as part of functional tests.

**Comment by juliakreger** [comment]
@Shrews Out of curiosity, I remember that you were using an 8GB machine for testing.  Do you remember how long it took the VM to boot?  Does the test playbook work for you in that VM?

I attempted to run it on a machine I have access to with 8 GB of RAM, and the results were... far from spectacular, although largely I believe that was due to the CPU performance of the system I was using.  Memory never appeared to be an issue with a single running VM.

**Comment by Shrews** [comment]
I haven't tried the test playbook. I remember the VM taking a looong time boot, but I don't recall how long it took. It seemed longer than the VMs from devstack. Mine was an 8GB *virtual* machine, though, as I tested it on an HP Cloud instance. VMs within VMs will naturally be slow, anyway.

**Comment by juliakreger** [comment]
@Shrews I'm thinking the direction to head in is to see if we can shift to a minimal image and incorporate Monty's disk image builder element for network config so Cloud-init is not required, and hopefully we end up with a smaller required memory footprint.  The physical host I was using that was limited to 8GB would not deploy CoreOS due to CPU performance issues.  CoreOS would actually time out.  If I remember correctly, your last test did reach active successfully.

**Comment by juliakreger** [comment]
Closing as this is super out of date. Bifrost is now in the OpenStack community as well, https://opendev.org/openstack/bifrost
